export const colorOptions = [
  { colorName: 'rose', hex: '#fda4af' },
  { colorName: 'pink', hex: '#f9a8d4' },
  { colorName: 'fuchsia', hex: '#f0abfc' },
  { colorName: 'purple', hex: '#d8b4fe' },
  { colorName: 'violet', hex: '#c4b5fd' },
  { colorName: 'indigo', hex: '#a5b4fc' },
  { colorName: 'blue', hex: '#93c5fd' },
  { colorName: 'lightBlue', hex: '#7dd3fc' },
  { colorName: 'cyan', hex: '#67e8f9' },
  { colorName: 'teal', hex: '#5eead4' },
  { colorName: 'emerald', hex: '#6ee7b7' },
  { colorName: 'green', hex: '#86efac' },
  { colorName: 'lime', hex: '#bef264' },
  { colorName: 'yellow', hex: '#fde047' },
  { colorName: 'amber', hex: '#fcd34d' },
  { colorName: 'orange', hex: '#fdba74' },
  { colorName: 'red', hex: '#ef4444' },
  { colorName: 'warmGray', hex: '#d6d3d1' },
]
